version: '3'

services:
  frontend:
    command: npm run start
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  api:
    command: npm run dev
    volumes:
      - ./api/src:/usr/src/app/src
